sonar.projectKey=tscz_transcribe
sonar.organization=tscz
sonar.projectName=transcribe
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.ts,**/*.test.tsx
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
