@startuml Application State Overview

title     Application State Overview

frame "Application" {

    package "Redux State" {
        package "Runtime State" {
            [Dialogs]
            [Audio]
        }
        package "Persisted State" {
            [Analysis]
            [Project]
        }
    }

    package AudioMiddleware {
        [AudioPlayer (Tone.js)]
        [Waveform (Peaks.js)]
    }

    package DialogManagement {
        [Dialog]
    }

    package  Api {
        [Persistence Api]
    }

}

frame "File System" {
    [Project File]
}

[Project] --> [Persistence Api]
[Analysis] --> [Persistence Api] 
[Persistence Api] --> [Project File] : save
[Persistence Api] <-- [Project File] : open
[Dialogs] --> [Dialog]
[Analysis] --> [Waveform (Peaks.js)]
[Audio] --> [AudioPlayer (Tone.js)]

@enduml