name: Build application

on: [push]

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm ci
    - name: Build the app
      run: |
        npm run build
    - name: Verify code formatting rules
      run: |
        npm run lint
    - name: Build the storybook
      run: |
        npm run build-storybook
    - name: Run all tests with code coverage
      run: |
        npm run coverage
    - name: Deploy coverage results to Coveralls 
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
