name: Deploy release

on:
  release:
    types: [published]

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Prepare dependencies
      run: |
        npm install -g yarn
        yarn install --frozen-lockfile --network-timeout 500000
    - name: Build release
      run: |
        npm run build
    - name: Deploy Application on Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        branch: gh-pages
        folder: build
