name: Deploy storybook

on:
  release:
    types: [published]

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Prepare dependencies
      run: |
        npm install -g yarn 
        yarn install --frozen-lockfile --network-timeout 500000
    - name: Build storybook
      run: |
        npm run build-storybook
    - name: Deploy Storybook on Github Branch
      uses: JamesIves/github-pages-deploy-action@3.0.4
      with:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        BRANCH: storybook
        FOLDER: build-storybook