name: Deploy storybook

on:
  release:
    types: [published]

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Prepare dependencies
      run: |
        npm install -g yarn
        yarn install --frozen-lockfile --network-timeout 500000
    - name: Build storybook
      run: |
        npm run build-storybook
    - name: Deploy Storybook on Github Branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        branch: storybook
        folder: build-storybook
